services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app-container
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
    depends_on:
      - mysql-test
    networks:
      - laravel-net

  mysql-test:
    image: mysql:8.0
    container_name: laravel-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: laravel
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel-net

volumes:
  db_data:

networks:
  laravel-net:
    driver: bridge
